# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
# IP: The module: 'base_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
# IP: The module: 'base_ps7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_ps7_0_0/base_ps7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_ps7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
