# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_audio_direct_0_3/base_audio_direct_0_3.xci
# IP: The module: 'base_audio_direct_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_0_1/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_1_1/fifo_generator_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_0_1/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_1_1/fifo_generator_1.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_audio_direct_0_3/base_audio_direct_0_3.xci
# IP: The module: 'base_audio_direct_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_0_1/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_1_1/fifo_generator_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_0_1/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Xilinx/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_1_1/fifo_generator_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
