# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/base/base.xdc

# Block Designs: bd/base/base.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base || ORIG_REF_NAME==base} -quiet] -quiet

# IP: bd/base/ip/base_audio_path_sel_0/base_audio_path_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_audio_path_sel_0 || ORIG_REF_NAME==base_audio_path_sel_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_0/base_ps7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_0 || ORIG_REF_NAME==base_ps7_0_0} -quiet] -quiet

# IP: bd/base/ip/base_xbar_0/base_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_xbar_0 || ORIG_REF_NAME==base_xbar_0} -quiet] -quiet

# IP: bd/base/ip/base_ps7_0_axi_periph_0/base_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ps7_0_axi_periph_0 || ORIG_REF_NAME==base_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_100M_0/base_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_0 || ORIG_REF_NAME==base_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/base/ip/base_rst_ps7_0_100M_1_0/base_rst_ps7_0_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_rst_ps7_0_100M_1_0 || ORIG_REF_NAME==base_rst_ps7_0_100M_1_0} -quiet] -quiet

# IP: bd/base/ip/base_ila_0_1/base_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_ila_0_1 || ORIG_REF_NAME==base_ila_0_1} -quiet] -quiet

# IP: bd/base/ip/base_pdm_microphone_0_2/base_pdm_microphone_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_pdm_microphone_0_2 || ORIG_REF_NAME==base_pdm_microphone_0_2} -quiet] -quiet

# IP: bd/base/ip/base_audio_direct_0_3/base_audio_direct_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_audio_direct_0_3 || ORIG_REF_NAME==base_audio_direct_0_3} -quiet] -quiet

# IP: bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_axi_gpio_0_2 || ORIG_REF_NAME==base_axi_gpio_0_2} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_0/base_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_0 || ORIG_REF_NAME==base_auto_pc_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_cc_0/base_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_cc_0 || ORIG_REF_NAME==base_auto_cc_0} -quiet] -quiet

# IP: bd/base/ip/base_auto_pc_1/base_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_auto_pc_1 || ORIG_REF_NAME==base_auto_pc_1} -quiet] -quiet

# IP: bd/base/ip/base_s00_mmu_0/base_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_s00_mmu_0 || ORIG_REF_NAME==base_s00_mmu_0} -quiet] -quiet

# IP: bd/base/ip/base_s01_mmu_0/base_s01_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==base_s01_mmu_0 || ORIG_REF_NAME==base_s01_mmu_0} -quiet] -quiet

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/base_ooc.xdc
