# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_pdm_microphone_0_2/base_pdm_microphone_0_2.xci
# IP: The module: 'base_pdm_microphone_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/cic_compiler_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet

# IP: C:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_pdm_microphone_0_2/base_pdm_microphone_0_2.xci
# IP: The module: 'base_pdm_microphone_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/cic_compiler_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cic_compiler_0 || ORIG_REF_NAME==cic_compiler_0} -quiet] -quiet
