#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : base.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon Feb 02 15:54:30 +0000 2026
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: base.sh [-help]
# usage: base.sh [-lib_map_path]
# usage: base.sh [-noclean_files]
# usage: base.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'base.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm xlslice_v1_0_2 xil_defaultlib axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xbip_utils_v3_0_10 axi_utils_v2_0_6 cic_compiler_v4_0_15 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 axi_mmu_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "base.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_audio_path_sel_0/sim/base_audio_path_sel_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_ps7_0_0/sim/base_ps7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_xbar_0/sim/base_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_rst_ps7_0_100M_0/sim/base_rst_ps7_0_100M_0.vhd" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_rst_ps7_0_100M_1_0/sim/base_rst_ps7_0_100M_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_ila_0_1/sim/base_ila_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work cic_compiler_v4_0_15 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/hdl/cic_compiler_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/ip/cic_compiler_0/sim/cic_compiler_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/cf25/new/pdm_clk_gen.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/cf25/imports/Downloads/pdm_mic.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_pdm_microphone_0_2/sim/base_pdm_microphone_0_2.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_0_1/sim/fifo_generator_0.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/src/fifo_generator_1_1/sim/fifo_generator_1.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/dbdf/src/PdmDes.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/dbdf/src/PdmSer.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/dbdf/src/audio_direct_path.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/Pynq-Z1/base/audio_direct_v1_1_S00_AXI.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/Pynq-Z1/base/pdm_rxtx.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/Pynq-Z1/base/pdm_ser.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/dbdf/hdl/audio_direct_v1_1.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_audio_direct_0_3/sim/base_audio_direct_0_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/sim/base_axi_gpio_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_auto_pc_0/sim/base_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_auto_cc_0/sim/base_auto_cc_0.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_auto_pc_1/sim/base_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_mmu_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/88c9/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/1b7e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/122e/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/b205/hdl/verilog" +incdir+"$ref_dir/../../../../project_1.gen/sources_1/bd/base/ipshared/c968/hdl/verilog" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_s00_mmu_0/sim/base_s00_mmu_0.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/ip/base_s01_mmu_0/sim/base_s01_mmu_0.v" \
    "$ref_dir/../../../../project_1.gen/sources_1/bd/base/sim/base.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.base xil_defaultlib.glbl -o base_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./base_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./base.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key base_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc base_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./base.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: base.sh [-help]\n\
Usage: base.sh [-lib_map_path]\n\
Usage: base.sh [-reset_run]\n\
Usage: base.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
