# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
# IP: The module: 'base_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.srcs/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xci
# IP: The module: 'base_axi_gpio_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/soseb/Downloads/wetransfer_labs_2026-02-02_1352/PYNQ/boards/Pynq-Z1/base/myproj/project_1.gen/sources_1/bd/base/ip/base_axi_gpio_0_2/base_axi_gpio_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_axi_gpio_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
